name: flutter_mapbox_navigation_plus
description: >
  Biko-maintained fork of flutter_mapbox_navigation_plus with embedded Mapbox
  navigation and planned Navigation SDK v3 support.
version: 1.1.0-biko.2
repository: https://github.com/biko-app/flutter_mapbox_navigation_plus
publish_to: none

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eopeter.fluttermapboxnavigation
        pluginClass: FlutterMapboxNavigationPlugin
      ios:
        pluginClass: FlutterMapboxNavigationPlugin
 #      linux:
 #        pluginClass: FlutterMapboxNavigationPlugin
 #      macos:
 #        pluginClass: FlutterMapboxNavigationPlugin
 #      windows:
 #        pluginClass: FlutterMapboxNavigationPluginCApi
 #      web:
 #        pluginClass: FlutterMapboxNavigationWeb
 #        fileName: flutter_mapbox_navigation_web.dart
